spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  #======================================
  # MySQL 配置项
  #
  datasource:
    url: jdbc:mysql://119.23.149.25:3306/nooblog_ex?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: Daedalus@130
    initial-size: 5
    max-idle: 10
    min-idle: 5
    max-wait: 10000

  #======================================
  # Redis 配置项
  #
  redis:
    database: 0
    host: 119.23.149.25
    port: 6379
    password: daedalus
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 4
      min-idle: 0

  #========================
  # 前端模板配置
  thymeleaf:
    cache: false
    mode: HTML5



server:
  tomcat:
    uri-encoding: UTF-8

